language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gfortan #for silo
      - libhdf5-serial-dev #for silo
      - liblapack-dev
      - libblas-dev
      - libboost-dev
      - gcc-4.9
      - g++-4.9

env:
  matrix: 
    - SILO=yes FLANN=no   REDIS=no  TWEMPROXY=no
    - SILO=yes FLANN=yes  REDIS=no  TWEMPROXY=no
    - SILO=yes FLANN=no   REDIS=yes TWEMPROXY=yes
    - SILO=yes FLANN=yes  REDIS=yes TWEMPROXY=yes
    - SILO=yes FLANN=no   REDIS=no  TWEMPROXY=no TESTFILE=test.json SILODIFF=/bin/true
    - SILO=yes FLANN=yes  REDIS=no  TWEMPROXY=no TESTFILE=test.json SILODIFF=/bin/true
    - SILO=yes FLANN=no   REDIS=yes TWEMPROXY=yes TESTFILE=test.json SILODIFF=/bin/true
    - SILO=yes FLANN=yes  REDIS=yes TWEMPROXY=yes TESTFILE=test.json SILODIFF=/bin/true
    - SILO=yes FLANN=no   REDIS=no  TWEMPROXY=no   TESTFILE=reftest4.json
    - SILO=yes FLANN=yes  REDIS=no  TWEMPROXY=no   TESTFILE=reftest4.json
    - SILO=yes FLANN=no   REDIS=yes TWEMPROXY=yes  TESTFILE=reftest4.json
    - SILO=yes FLANN=yes  REDIS=yes TWEMPROXY=yes  TESTFILE=reftest4.json
    - SILO=no  FLANN=no   REDIS=no  TWEMPROXY=no SILODIFF=/bin/true

before_script:
  - export CXX="g++-4.9" CC="gcc-4.9";
  - export PATH="/usr/lib/ccache:$PATH"
  - wget -O - http://charm.cs.illinois.edu/distrib/charm-6.6.1.tar.gz | tar -xz 
  - cd charm && ./build charm++ net-linux-x86_64 -j4 && export CHARM_ROOT=$PWD && cd ..

script:
  - make -j2 REDIS=${REDIS} FLANN=${FLANN} SILO=${SILO} CHARM_ROOT=${CHARM_ROOT} && 
    make get_reference &&
    make test REDIS=${REDIS} FLANN=${FLANN} SILO=${SILO} ${TESTFILE:+TESTFILE=${TESTFILE}} ${SILODIFF:+SILODIFF=${SILODIFF}}

cache:
  directories:
    - $HOME/.ccache

compiler:
  - gcc

notifications:
  email:
    - tabasco-dev@lanl.gov  
